bits = [
  'bargraph',
  'bend-sensor',
  'branch',
  'bright-led',
  'button',
  'buzzer',
  'coin-battery',
  'dc-motor',
  'dimmer',
  'doubleand',
  'doubleor',
  'fan',
  'forkinverter',
  'led',
  'light-sensor',
  'light-trigger',
  'light-wire',
  'long-led',
  'motion-trigger',
  'power',
  'pressure-sensor',
  'pulse',
  'rgb-led',
  'roller-switch',
  'servo-motor',
  'slide-dimmer',
  'slide-switch',
  'sound-trigger',
  'temperature-sensor',
  'timeout',
  'toggle-switch',
  'usb-power',
  'uv-led',
  'vibration-motor',
  'wire'
]

bits.each do |bit|
  Bit.create(name: bit)
end